import { Platform, Dimensions } from 'react-native';
const { width, height } = Dimensions.get('window');

export default {
  wrapper: {
    flex: 1,
    backgroundColor: '#FFF',
    marginTop: 1,
  },
  imageView: {
    marginTop: 10,
    alignItems: 'center',
    overflow: 'hidden',
    marginLeft: 12,
    marginRight: 12,
    paddingBottom: 0,
    elevation: 1.5,
  },
  image: {
    borderRadius: 10,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  cardMain: {
    height: (width < 330) ? ((Platform.OS === 'ios') ? (height / 1.8) : (height / 1.9)) : ((Platform.OS === 'ios') ? (height / 1.6) : (height / 1.75)),
    resizeMode: 'cover',
    flex: 1,
    width: null,
  },
  subtextLeft: {
    fontSize: 13,
    color: '#393E40',
    fontWeight: '600',
    opacity: 0.879,
    fontFamily: 'arial',
  },
  textLeft: {
    fontSize: 16,
    color: '#393E40',
    fontWeight: '600',
    opacity: 0.879,
    fontFamily: 'arial',
  },
  subText: {
    backgroundColor: '#FFFFFF',
    padding: 10,
    paddingBottom: 15,
    marginLeft: 10,
    marginRight: 10,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    shadowOpacity: 0.125,
    shadowRadius: 3,
    shadowOffset: {
      height: 1,
      width: 0,
    },
  },
  bottomGrid: {
    position: 'absolute',
    bottom: 10,
    left: 0,
    right: 0,
  },
  workplace: {
    backgroundColor: 'red',
    alignSelf: 'center',
    justifyContent: 'space-between',
    marginTop: -10,
    paddingLeft: 10,
    elevation: 2,
  },
  bottomRoundedPills: {
    borderRadius: 33,
    height: 65,
    width: 65,
    backgroundColor: 'white',
    paddingTop: 15,
    elevation: 3,
    alignItems: 'center',
    shadowOpacity: 0.2,
    shadowRadius: 3,
    borderColor: '#aaa',
    borderWidth: (Platform.OS === 'ios') ? undefined : 0.2,
    shadowOffset: {
      height: 2,
      width: 1,
    },
  },
  bottomRoundedSmallPills: {
    borderRadius: 25,
    marginTop: 8,
    height: 50,
    width: 50,
    backgroundColor: 'white',
    paddingTop: 8,
    elevation: 3,
    justifyContent: 'center',
    alignItems: 'center',
    shadowOpacity: 0.2,
    shadowRadius: 3,
    borderColor: '#aaa',
    borderWidth: (Platform.OS === 'ios') ? undefined : 0.2,
    shadowOffset: {
      height: 2,
      width: 1,
    },
  },
  bottomRowStyle: {
    marginTop: (Platform.OS === 'android') ? 5 : 10,
    justifyContent: 'space-around',
  },
  bookBtn: {},
};
