import { Platform, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export default {
  imageView: {
    alignItems: 'center',
    padding: 10,
    paddingBottom: 0,
  },
  image: {
    height: height / 1.5,
    width,
  },
  subText: {
    backgroundColor: 'white',
    width,
    alignSelf: 'center',
    flexDirection: 'column',
    justifyContent: 'space-around',
    padding: 10,
    borderBottomColor: '#ccc',
    borderBottomWidth: 1,
  },
  name: {
    fontSize: 20,
    fontWeight: '800',
    color: 'rgba(0,0,0,0.75)',
  },
  distanceAwayText: {
    fontSize: 12,
    color: 'rgba(0,0,0,0.3)',
    fontWeight: '600',
  },
  workingText: {
    fontSize: 16,
    color: 'rgba(0,0,0,0.85)',
  },
  quote: {
    padding: 15,
    backgroundColor: 'white',
    borderBottomColor: '#ccc',
    borderBottomWidth: 1,
  },
  distanceAwayText2: {
    color: 'rgba(0,0,0,0.5)',
    fontWeight: '400',
  },
  instagramPhotoCount: {
    backgroundColor: 'white',
    padding: 15,
  },
  instagramPhotosCarousel: {
    height: height / 1.5,
    justifyContent: 'space-between',
    borderBottomColor: 'rgba(0,0,0,0.3)',
    borderBottomWidth: 0.8,
    backgroundColor: 'white',
  },
  sixThumbnailsInCarousel: {
    flexWrap: 'wrap',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    marginHorizontal: 5,
  },
  thumbnailView: {},
  interestTextHeading: {
    padding: 15,
    paddingBottom: 5,
    backgroundColor: 'white',
  },
  interestsView: {
    flexDirection: 'row',
    // alignItems:'center',
    backgroundColor: 'white',
    flexWrap: 'wrap',
    padding: 13,
    paddingBottom: 80,
  },
  interestTextView: {
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FC432F',
    height: 50,
    marginRight: 5,
    marginBottom: 10,
    borderRadius: 8,
    paddingHorizontal: 4,
    paddingVertical: 4,
  },

  interestText: {
    color: '#F7524C',
    margin: 10,
  },
  thumbnail: {
    width: (width / 3) - 15,
    height: (width / 3) - 15,
    borderRadius: 5,
    marginVertical: 5,
  },
  grid: {
    backgroundColor: 'blue',
  },
  row: {
    height: 100,
    backgroundColor: 'white',
    justifyContent: 'space-between',
    padding: 10,
  },
  wrapper: {
    height: height / 1.5,
  },
  wrapper2: {},
  dot: {
    backgroundColor: 'rgba(255,255,255,0.5)',
    width: 6,
    height: 6,
    borderRadius: 4,
    marginLeft: 3,
    marginRight: 3,
    marginTop: 3,
    marginBottom: 3,
  },
  activeDot: {
    backgroundColor: '#F7524C',
    width: 6,
    height: 6,
    borderRadius: 4,
    marginLeft: 3,
    marginRight: 3,
    marginTop: 3,
    marginBottom: 3,
  },
  slide: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#9DD6EB',
  },
  paginationStyle: {
    position: 'absolute',
    width: (Platform.OS === 'android') ? width : width - 30,
    justifyContent: (Platform.OS === 'android') ? 'center' : 'flex-end',
    alignSelf: (Platform.OS === 'android') ? 'center' : 'flex-end',
    height: 30,
    top: (Platform.OS === 'android') ? undefined : -39,
    bottom: (Platform.OS === 'android') ? 10 : undefined,
    right: (Platform.OS === 'android') ? 0 : 20,
  },
  thumbnailDot: {
    backgroundColor: (Platform.OS === 'android') ? 'rgba(0,0,0,0.5)' : 'rgba(0,0,0,0.3)',
    width: (Platform.OS === 'android') ? 10 : 6,
    height: (Platform.OS === 'android') ? 10 : 6,
    borderRadius: 4,
    marginLeft: 3,
    marginRight: 3,
    marginTop: 3,
    marginBottom: 3,
  },
  activeThumbnailDot: {
    backgroundColor: '#F7524C',
    width: (Platform.OS === 'android') ? 10 : 6,
    height: (Platform.OS === 'android') ? 10 : 6,
    borderRadius: 4,
    marginLeft: 3,
    marginRight: 3,
    marginTop: 3,
    marginBottom: 3,
  },
  bottomPillsView: {
    backgroundColor: 'rgba(255,255,255,0)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 10,
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
  },
  bottomGrid: {},
  bottomRoundedSalmonPills: {
    borderRadius: 27.5,
    height: 55,
    width: 55,
    backgroundColor: 'salmon',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomRoundedBluePills: {
    borderRadius: 27.5,
    height: 55,
    width: 55,
    backgroundColor: '#59DBB6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomRoundedSpringGreenPills: {
    borderRadius: 27.5,
    height: 55,
    width: 55,
    backgroundColor: '#28B8F6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bottomRowStyle: {
    justifyContent: 'space-around',
    padding: 18,
    paddingVertical: 10,
  },
};
